name: דיווח באג
description: באג הוא תקלה או פעולה לא צפויה שקורה במערכת
title: "[בעייה]: "
labels: ["באג", "ללא מענה"]
projects: ["tgilabs/8"]
assignees:
  - webmasters
  - thefourcraft
  - JustMe-png

body:
  - type: markdown
    attributes:
      value: |
        <div dir='rtl'>      

        תודה על כך שאתם מקדישים זמן למלא את הדו״ח הזה ולשפר את הפלטפורמה שלנו. נשתדל לטפל בבעיה בהקדם האפשרי.
        (https://github.com/orgs/tgilabs/projects/8)[אפשר לעקוב אחר התקדמות הבעיה בפרויקט שלנו [בגיטהאב.
        
  - type: textarea
    id: what-happened
    attributes:
      label: מה קרה?
      description: בבקשה תארו מה קרה בצורה הטובה ביותר
      placeholder: ספרו לנו מה אתם רואים
      value: "היה בעייה! כשאני מנסה לעשות X, קורה Y"
    validations:
      required: true
  - type: dropdown
    id: location
    attributes:
      label: היכן קרה הבעיה?
      description: באיזה מערכת בפלטפורמה מתרחשת הבעיה?
      options:
        - צ׳אט
        - פרופיל אישי
        - התחברות למערכת
        - התחברות בעזרת רשת חברתית
        - אנליטיקה
        - מדריך למשתמש
        - לינק שבור
        - קוד תמיכה ביוצר
        - עוגיות
        - תשלום בעזרת פייפאל
        - תשלום בעזרת כרטיס אשראי
        - תשלום בעזרת bit
        - תשלום בעזרת google pay
        - תשלום בעזרת apple pay
        - מערכת סימול מודעות כאהובות
        - מערכת הפוסטים הראשית
        - מערכת הביקורות
        - מערכת הזמנת פרוייקט אישי
        - מערכת תגיות
        - מערכת פרסום מודעות
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: באיזה דפדפן מתרחשת הבעיה?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Arc
  - type: dropdown
    id: device
    attributes:
      label: סוג המכשיר
      multiple: true
      options:
        - Smartphone (Android)
        - Smartphone (Apple)
        - Tablet (Android)
        - Tablet (Apple)
        - PC (Windows)
        - PC (Mac)
        - WorkWay App
